// cz EE GR LV LT PL SK SI IN

// US','AU','AT','BE','CZ','DK','EE',
// 'FI','FR','DE','GR','IE','IT',
// 'LV','LT','LU','NL','NZ','NO',
// 'PL','PT','SK','SI','ES','SE','CH',
// 'GB','IN'

module.exports.countrySeed = [
  {_id : "1",shortName : "AF",longName : "Afghanistan",iso3 : "AFG",numberCode : "4",phoneCode : "93"},
  {_id : "2",shortName : "AL",longName : "Albania",iso3 : "ALB",numberCode : "8",phoneCode : "355"},
  {_id : "3",shortName : "DZ",longName : "Algeria",iso3 : "DZA",numberCode : "12",phoneCode : "213"},
  {_id : "4",shortName : "AS",longName : "American Samoa",iso3 : "ASM",numberCode : "16",phoneCode : "1684"},
  {_id : "5",shortName : "AD",longName : "Andorra",iso3 : "AND",numberCode : "20",phoneCode : "376"},
  {_id : "6",shortName : "AO",longName : "Angola",iso3 : "AGO",numberCode : "24",phoneCode : "244"},
  {_id : "7",shortName : "AI",longName : "Anguilla",iso3 : "AIA",numberCode : "660",phoneCode : "1264"},
  {_id : "8",shortName : "AQ",longName : "Antarctica",iso3 : "",numberCode : "",phoneCode : "0"},
  {_id : "9",shortName : "AG",longName : "Antigua and Barbuda",iso3 : "ATG",numberCode : "28",phoneCode : "1268"},
  {_id : "10",shortName : "AR",longName : "Argentina",iso3 : "ARG",numberCode : "32",phoneCode : "54"},
  {_id : "11",shortName : "AM",longName : "Armenia",iso3 : "ARM",numberCode : "51",phoneCode : "374"},
  {_id : "12",shortName : "AW",longName : "Aruba",iso3 : "ABW",numberCode : "533",phoneCode : "297"},
  {_id : "13",shortName : "AU",longName : "Australia",iso3 : "AUS",numberCode : "36",phoneCode : "61"},
  {_id : "14",shortName : "AT",longName : "Austria",iso3 : "AUT",numberCode : "40",phoneCode : "43"},
  {_id : "15",shortName : "AZ",longName : "Azerbaijan",iso3 : "AZE",numberCode : "31",phoneCode : "994"},
  {_id : "16",shortName : "BS",longName : "Bahamas",iso3 : "BHS",numberCode : "44",phoneCode : "1242"},
  {_id : "17",shortName : "BH",longName : "Bahrain",iso3 : "BHR",numberCode : "48",phoneCode : "973"},
  {_id : "18",shortName : "BD",longName : "Bangladesh",iso3 : "BGD",numberCode : "50",phoneCode : "880"},
  {_id : "19",shortName : "BB",longName : "Barbados",iso3 : "BRB",numberCode : "52",phoneCode : "1246"},
  {_id : "20",shortName : "BY",longName : "Belarus",iso3 : "BLR",numberCode : "112",phoneCode : "375"},
  {_id : "21",shortName : "BE",longName : "Belgium",iso3 : "BEL",numberCode : "56",phoneCode : "32"},
  {_id : "22",shortName : "BZ",longName : "Belize",iso3 : "BLZ",numberCode : "84",phoneCode : "501"},
  {_id : "23",shortName : "BJ",longName : "Benin",iso3 : "BEN",numberCode : "204",phoneCode : "229"},
  {_id : "24",shortName : "BM",longName : "Bermuda",iso3 : "BMU",numberCode : "60",phoneCode : "1441"},
  {_id : "25",shortName : "BT",longName : "Bhutan",iso3 : "BTN",numberCode : "64",phoneCode : "975"},
  {_id : "26",shortName : "BO",longName : "Bolivia",iso3 : "BOL",numberCode : "68",phoneCode : "591"},
  {_id : "27",shortName : "BA",longName : "Bosnia and Herzegovina",iso3 : "BIH",numberCode : "70",phoneCode : "387"},
  {_id : "28",shortName : "BW",longName : "Botswana",iso3 : "BWA",numberCode : "72",phoneCode : "267"},
  {_id : "29",shortName : "BV",longName : "Bouvet Island",iso3 : "",numberCode : "",phoneCode : "0"},
  {_id : "30",shortName : "BR",longName : "Brazil",iso3 : "BRA",numberCode : "76",phoneCode : "55"},
  {_id : "31",shortName : "IO",longName : "British Indian Ocean Territory",iso3 : "",numberCode : "",phoneCode : "246"},
  {_id : "32",shortName : "BN",longName : "Brunei Darussalam",iso3 : "BRN",numberCode : "96",phoneCode : "673"},
  {_id : "33",shortName : "BG",longName : "Bulgaria",iso3 : "BGR",numberCode : "100",phoneCode : "359"},
  {_id : "34",shortName : "BF",longName : "Burkina Faso",iso3 : "BFA",numberCode : "854",phoneCode : "226"},
  {_id : "35",shortName : "BI",longName : "Burundi",iso3 : "BDI",numberCode : "108",phoneCode : "257"},
  {_id : "36",shortName : "KH",longName : "Cambodia",iso3 : "KHM",numberCode : "116",phoneCode : "855"},
  {_id : "37",shortName : "CM",longName : "Cameroon",iso3 : "CMR",numberCode : "120",phoneCode : "237"},
  {_id : "38",shortName : "CA",longName : "Canada",iso3 : "CAN",numberCode : "124",phoneCode : "1"},
  {_id : "39",shortName : "CV",longName : "Cape Verde",iso3 : "CPV",numberCode : "132",phoneCode : "238"},
  {_id : "40",shortName : "KY",longName : "Cayman Islands",iso3 : "CYM",numberCode : "136",phoneCode : "1345"},
  {_id : "41",shortName : "CF",longName : "Central African Republic",iso3 : "CAF",numberCode : "140",phoneCode : "236"},
  {_id : "42",shortName : "TD",longName : "Chad",iso3 : "TCD",numberCode : "148",phoneCode : "235"},
  {_id : "43",shortName : "CL",longName : "Chile",iso3 : "CHL",numberCode : "152",phoneCode : "56"},
  {_id : "44",shortName : "CN",longName : "China",iso3 : "CHN",numberCode : "156",phoneCode : "86"},
  {_id : "45",shortName : "CX",longName : "Christmas Island",iso3 : "",numberCode : "",phoneCode : "61"},
  {_id : "46",shortName : "CC",longName : "Cocos (Keeling} Islands",iso3 : "",numberCode : "",phoneCode : "672"},
  {_id : "47",shortName : "CO",longName : "Colombia",iso3 : "COL",numberCode : "170",phoneCode : "57"},
  {_id : "48",shortName : "KM",longName : "Comoros",iso3 : "COM",numberCode : "174",phoneCode : "269"},
  {_id : "49",shortName : "CG",longName : "Congo",iso3 : "COG",numberCode : "178",phoneCode : "242"},
  {_id : "50",shortName : "CD",longName : "Congo, the Democratic Republic of the",iso3 : "COD",numberCode : "180",phoneCode : "242"},
  {_id : "51",shortName : "CK",longName : "Cook Islands",iso3 : "COK",numberCode : "184",phoneCode : "682"},
  {_id : "52",shortName : "CR",longName : "Costa Rica",iso3 : "CRI",numberCode : "188",phoneCode : "506"},
  {_id : "53",shortName : "CI",longName : "Cote D\"Ivoire",iso3 : "CIV",numberCode : "384",phoneCode : "225"},
  {_id : "54",shortName : "HR",longName : "Croatia",iso3 : "HRV",numberCode : "191",phoneCode : "385"},
  {_id : "55",shortName : "CU",longName : "Cuba",iso3 : "CUB",numberCode : "192",phoneCode : "53"},
  {_id : "56",shortName : "CY",longName : "Cyprus",iso3 : "CYP",numberCode : "196",phoneCode : "357"},
  {_id : "57",shortName : "CZ",longName : "Czech Republic",iso3 : "CZE",numberCode : "203",phoneCode : "420"},
  {_id : "58",shortName : "DK",longName : "Denmark",iso3 : "DNK",numberCode : "208",phoneCode : "45"},
  {_id : "59",shortName : "DJ",longName : "Djibouti",iso3 : "DJI",numberCode : "262",phoneCode : "253"},
  {_id : "60",shortName : "DM",longName : "Dominica",iso3 : "DMA",numberCode : "212",phoneCode : "1767"},
  {_id : "61",shortName : "DO",longName : "Dominican Republic",iso3 : "DOM",numberCode : "214",phoneCode : "1809"},
  {_id : "62",shortName : "EC",longName : "Ecuador",iso3 : "ECU",numberCode : "218",phoneCode : "593"},
  {_id : "63",shortName : "EG",longName : "Egypt",iso3 : "EGY",numberCode : "818",phoneCode : "20"},
  {_id : "64",shortName : "SV",longName : "El Salvador",iso3 : "SLV",numberCode : "222",phoneCode : "503"},
  {_id : "65",shortName : "GQ",longName : "Equatorial Guinea",iso3 : "GNQ",numberCode : "226",phoneCode : "240"},
  {_id : "66",shortName : "ER",longName : "Eritrea",iso3 : "ERI",numberCode : "232",phoneCode : "291"},
  {_id : "67",shortName : "EE",longName : "Estonia",iso3 : "EST",numberCode : "233",phoneCode : "372"},
  {_id : "68",shortName : "ET",longName : "Ethiopia",iso3 : "ETH",numberCode : "231",phoneCode : "251"},
  {_id : "69",shortName : "FK",longName : "Falkland Islands (Malvinas}",iso3 : "FLK",numberCode : "238",phoneCode : "500"},
  {_id : "70",shortName : "FO",longName : "Faroe Islands",iso3 : "FRO",numberCode : "234",phoneCode : "298"},
  {_id : "71",shortName : "FJ",longName : "Fiji",iso3 : "FJI",numberCode : "242",phoneCode : "679"},
  {_id : "72",shortName : "FI",longName : "Finland",iso3 : "FIN",numberCode : "246",phoneCode : "358"},
  {_id : "73",shortName : "FR",longName : "France",iso3 : "FRA",numberCode : "250",phoneCode : "33"},
  {_id : "74",shortName : "GF",longName : "French Guiana",iso3 : "GUF",numberCode : "254",phoneCode : "594"},
  {_id : "75",shortName : "PF",longName : "French Polynesia",iso3 : "PYF",numberCode : "258",phoneCode : "689"},
  {_id : "76",shortName : "TF",longName : "French Southern Territories",iso3 : "",numberCode : "",phoneCode : "0"},
  {_id : "77",shortName : "GA",longName : "Gabon",iso3 : "GAB",numberCode : "266",phoneCode : "241"},
  {_id : "78",shortName : "GM",longName : "Gambia",iso3 : "GMB",numberCode : "270",phoneCode : "220"},
  {_id : "79",shortName : "GE",longName : "Georgia",iso3 : "GEO",numberCode : "268",phoneCode : "995"},
  {_id : "80",shortName : "DE",longName : "Germany",iso3 : "DEU",numberCode : "276",phoneCode : "49"},
  {_id : "81",shortName : "GH",longName : "Ghana",iso3 : "GHA",numberCode : "288",phoneCode : "233"},
  {_id : "82",shortName : "GI",longName : "Gibraltar",iso3 : "GIB",numberCode : "292",phoneCode : "350"},
  {_id : "83",shortName : "GR",longName : "Greece",iso3 : "GRC",numberCode : "300",phoneCode : "30"},
  {_id : "84",shortName : "GL",longName : "Greenland",iso3 : "GRL",numberCode : "304",phoneCode : "299"},
  {_id : "85",shortName : "GD",longName : "Grenada",iso3 : "GRD",numberCode : "308",phoneCode : "1473"},
  {_id : "86",shortName : "GP",longName : "Guadeloupe",iso3 : "GLP",numberCode : "312",phoneCode : "590"},
  {_id : "87",shortName : "GU",longName : "Guam",iso3 : "GUM",numberCode : "316",phoneCode : "1671"},
  {_id : "88",shortName : "GT",longName : "Guatemala",iso3 : "GTM",numberCode : "320",phoneCode : "502"},
  {_id : "89",shortName : "GN",longName : "Guinea",iso3 : "GIN",numberCode : "324",phoneCode : "224"},
  {_id : "90",shortName : "GW",longName : "Guinea-Bissau",iso3 : "GNB",numberCode : "624",phoneCode : "245"},
  {_id : "91",shortName : "GY",longName : "Guyana",iso3 : "GUY",numberCode : "328",phoneCode : "592"},
  {_id : "92",shortName : "HT",longName : "Haiti",iso3 : "HTI",numberCode : "332",phoneCode : "509"},
  {_id : "93",shortName : "HM",longName : "Heard Island and Mcdonald Islands",iso3 : "",numberCode : "",phoneCode : "0"},
  {_id : "94",shortName : "VA",longName : "Holy See (Vatican City State}",iso3 : "VAT",numberCode : "336",phoneCode : "39"},
  {_id : "95",shortName : "HN",longName : "Honduras",iso3 : "HND",numberCode : "340",phoneCode : "504"},
  {_id : "96",shortName : "HK",longName : "Hong Kong",iso3 : "HKG",numberCode : "344",phoneCode : "852"},
  {_id : "97",shortName : "HU",longName : "Hungary",iso3 : "HUN",numberCode : "348",phoneCode : "36"},
  {_id : "98",shortName : "IS",longName : "Iceland",iso3 : "ISL",numberCode : "352",phoneCode : "354"},
  {_id : "99",shortName : "IN",longName : "India",iso3 : "IND",numberCode : "356",phoneCode : "91"},
  {_id : "100",shortName : "ID",longName : "Indonesia",iso3 : "IDN",numberCode : "360",phoneCode : "62"},
  {_id : "101",shortName : "IR",longName : "Iran, Islamic Republic of",iso3 : "IRN",numberCode : "364",phoneCode : "98"},
  {_id : "102",shortName : "IQ",longName : "Iraq",iso3 : "IRQ",numberCode : "368",phoneCode : "964"},
  {_id : "103",shortName : "IE",longName : "Ireland",iso3 : "IRL",numberCode : "372",phoneCode : "353"},
  {_id : "104",shortName : "IL",longName : "Israel",iso3 : "ISR",numberCode : "376",phoneCode : "972"},
  {_id : "105",shortName : "IT",longName : "Italy",iso3 : "ITA",numberCode : "380",phoneCode : "39"},
  {_id : "106",shortName : "JM",longName : "Jamaica",iso3 : "JAM",numberCode : "388",phoneCode : "1876"},
  {_id : "107",shortName : "JP",longName : "Japan",iso3 : "JPN",numberCode : "392",phoneCode : "81"},
  {_id : "108",shortName : "JO",longName : "Jordan",iso3 : "JOR",numberCode : "400",phoneCode : "962"},
  {_id : "109",shortName : "KZ",longName : "Kazakhstan",iso3 : "KAZ",numberCode : "398",phoneCode : "7"},
  {_id : "110",shortName : "KE",longName : "Kenya",iso3 : "KEN",numberCode : "404",phoneCode : "254"},
  {_id : "111",shortName : "KI",longName : "Kiribati",iso3 : "KIR",numberCode : "296",phoneCode : "686"},
  {_id : "112",shortName : "KP",longName : "Korea, Democratic People\"s Republic of",iso3 : "PRK",numberCode : "408",phoneCode : "850"},
  {_id : "113",shortName : "KR",longName : "Korea, Republic of",iso3 : "KOR",numberCode : "410",phoneCode : "82"},
  {_id : "114",shortName : "KW",longName : "Kuwait",iso3 : "KWT",numberCode : "414",phoneCode : "965"},
  {_id : "115",shortName : "KG",longName : "Kyrgyzstan",iso3 : "KGZ",numberCode : "417",phoneCode : "996"},
  {_id : "116",shortName : "LA",longName : "Lao People\"s Democratic Republic",iso3 : "LAO",numberCode : "418",phoneCode : "856"},
  {_id : "117",shortName : "LV",longName : "Latvia",iso3 : "LVA",numberCode : "428",phoneCode : "371"},
  {_id : "118",shortName : "LB",longName : "Lebanon",iso3 : "LBN",numberCode : "422",phoneCode : "961"},
  {_id : "119",shortName : "LS",longName : "Lesotho",iso3 : "LSO",numberCode : "426",phoneCode : "266"},
  {_id : "120",shortName : "LR",longName : "Liberia",iso3 : "LBR",numberCode : "430",phoneCode : "231"},
  {_id : "121",shortName : "LY",longName : "Libyan Arab Jamahiriya",iso3 : "LBY",numberCode : "434",phoneCode : "218"},
  {_id : "122",shortName : "LI",longName : "Liechtenstein",iso3 : "LIE",numberCode : "438",phoneCode : "423"},
  {_id : "123",shortName : "LT",longName : "Lithuania",iso3 : "LTU",numberCode : "440",phoneCode : "370"},
  {_id : "124",shortName : "LU",longName : "Luxembourg",iso3 : "LUX",numberCode : "442",phoneCode : "352"},
  {_id : "125",shortName : "MO",longName : "Macao",iso3 : "MAC",numberCode : "446",phoneCode : "853"},
  {_id : "126",shortName : "MK",longName : "Macedonia, the Former Yugoslav Republic of",iso3 : "MKD",numberCode : "807",phoneCode : "389"},
  {_id : "127",shortName : "MG",longName : "Madagascar",iso3 : "MDG",numberCode : "450",phoneCode : "261"},
  {_id : "128",shortName : "MW",longName : "Malawi",iso3 : "MWI",numberCode : "454",phoneCode : "265"},
  {_id : "129",shortName : "MY",longName : "Malaysia",iso3 : "MYS",numberCode : "458",phoneCode : "60"},
  {_id : "130",shortName : "MV",longName : "Maldives",iso3 : "MDV",numberCode : "462",phoneCode : "960"},
  {_id : "131",shortName : "ML",longName : "Mali",iso3 : "MLI",numberCode : "466",phoneCode : "223"},
  {_id : "132",shortName : "MT",longName : "Malta",iso3 : "MLT",numberCode : "470",phoneCode : "356"},
  {_id : "133",shortName : "MH",longName : "Marshall Islands",iso3 : "MHL",numberCode : "584",phoneCode : "692"},
  {_id : "134",shortName : "MQ",longName : "Martinique",iso3 : "MTQ",numberCode : "474",phoneCode : "596"},
  {_id : "135",shortName : "MR",longName : "Mauritania",iso3 : "MRT",numberCode : "478",phoneCode : "222"},
  {_id : "136",shortName : "MU",longName : "Mauritius",iso3 : "MUS",numberCode : "480",phoneCode : "230"},
  {_id : "137",shortName : "YT",longName : "Mayotte",iso3 : "",numberCode : "",phoneCode : "269"},
  {_id : "138",shortName : "MX",longName : "Mexico",iso3 : "MEX",numberCode : "484",phoneCode : "52"},
  {_id : "139",shortName : "FM",longName : "Micronesia, Federated States of",iso3 : "FSM",numberCode : "583",phoneCode : "691"},
  {_id : "140",shortName : "MD",longName : "Moldova, Republic of",iso3 : "MDA",numberCode : "498",phoneCode : "373"},
  {_id : "141",shortName : "MC",longName : "Monaco",iso3 : "MCO",numberCode : "492",phoneCode : "377"},
  {_id : "142",shortName : "MN",longName : "Mongolia",iso3 : "MNG",numberCode : "496",phoneCode : "976"},
  {_id : "143",shortName : "MS",longName : "Montserrat",iso3 : "MSR",numberCode : "500",phoneCode : "1664"},
  {_id : "144",shortName : "MA",longName : "Morocco",iso3 : "MAR",numberCode : "504",phoneCode : "212"},
  {_id : "145",shortName : "MZ",longName : "Mozambique",iso3 : "MOZ",numberCode : "508",phoneCode : "258"},
  {_id : "146",shortName : "MM",longName : "Myanmar",iso3 : "MMR",numberCode : "104",phoneCode : "95"},
  {_id : "147",shortName : "NA",longName : "Namibia",iso3 : "NAM",numberCode : "516",phoneCode : "264"},
  {_id : "148",shortName : "NR",longName : "Nauru",iso3 : "NRU",numberCode : "520",phoneCode : "674"},
  {_id : "149",shortName : "NP",longName : "Nepal",iso3 : "NPL",numberCode : "524",phoneCode : "977"},
  {_id : "150",shortName : "NL",longName : "Netherlands",iso3 : "NLD",numberCode : "528",phoneCode : "31"},
  {_id : "151",shortName : "AN",longName : "Netherlands Antilles",iso3 : "ANT",numberCode : "530",phoneCode : "599"},
  {_id : "152",shortName : "NC",longName : "New Caledonia",iso3 : "NCL",numberCode : "540",phoneCode : "687"},
  {_id : "153",shortName : "NZ",longName : "New Zealand",iso3 : "NZL",numberCode : "554",phoneCode : "64"},
  {_id : "154",shortName : "NI",longName : "Nicaragua",iso3 : "NIC",numberCode : "558",phoneCode : "505"},
  {_id : "155",shortName : "NE",longName : "Niger",iso3 : "NER",numberCode : "562",phoneCode : "227"},
  {_id : "156",shortName : "NG",longName : "Nigeria",iso3 : "NGA",numberCode : "566",phoneCode : "234"},
  {_id : "157",shortName : "NU",longName : "Niue",iso3 : "NIU",numberCode : "570",phoneCode : "683"},
  {_id : "158",shortName : "NF",longName : "Norfolk Island",iso3 : "NFK",numberCode : "574",phoneCode : "672"},
  {_id : "159",shortName : "MP",longName : "Northern Mariana Islands",iso3 : "MNP",numberCode : "580",phoneCode : "1670"},
  {_id : "160",shortName : "NO",longName : "Norway",iso3 : "NOR",numberCode : "578",phoneCode : "47"},
  {_id : "161",shortName : "OM",longName : "Oman",iso3 : "OMN",numberCode : "512",phoneCode : "968"},
  {_id : "162",shortName : "PK",longName : "Pakistan",iso3 : "PAK",numberCode : "586",phoneCode : "92"},
  {_id : "163",shortName : "PW",longName : "Palau",iso3 : "PLW",numberCode : "585",phoneCode : "680"},
  {_id : "164",shortName : "PS",longName : "Palestinian Territory, Occupied",iso3 : "",numberCode : "",phoneCode : "970"},
  {_id : "165",shortName : "PA",longName : "Panama",iso3 : "PAN",numberCode : "591",phoneCode : "507"},
  {_id : "166",shortName : "PG",longName : "Papua New Guinea",iso3 : "PNG",numberCode : "598",phoneCode : "675"},
  {_id : "167",shortName : "PY",longName : "Paraguay",iso3 : "PRY",numberCode : "600",phoneCode : "595"},
  {_id : "168",shortName : "PE",longName : "Peru",iso3 : "PER",numberCode : "604",phoneCode : "51"},
  {_id : "169",shortName : "PH",longName : "Philippines",iso3 : "PHL",numberCode : "608",phoneCode : "63"},
  {_id : "170",shortName : "PN",longName : "Pitcairn",iso3 : "PCN",numberCode : "612",phoneCode : "0"},
  {_id : "171",shortName : "PL",longName : "Poland",iso3 : "POL",numberCode : "616",phoneCode : "48"},
  {_id : "172",shortName : "PT",longName : "Portugal",iso3 : "PRT",numberCode : "620",phoneCode : "351"},
  {_id : "173",shortName : "PR",longName : "Puerto Rico",iso3 : "PRI",numberCode : "630",phoneCode : "1787"},
  {_id : "174",shortName : "QA",longName : "Qatar",iso3 : "QAT",numberCode : "634",phoneCode : "974"},
  {_id : "175",shortName : "RE",longName : "Reunion",iso3 : "REU",numberCode : "638",phoneCode : "262"},
  {_id : "176",shortName : "RO",longName : "Romania",iso3 : "ROM",numberCode : "642",phoneCode : "40"},
  {_id : "177",shortName : "RU",longName : "Russian Federation",iso3 : "RUS",numberCode : "643",phoneCode : "70"},
  {_id : "178",shortName : "RW",longName : "Rwanda",iso3 : "RWA",numberCode : "646",phoneCode : "250"},
  {_id : "179",shortName : "SH",longName : "Saint Helena",iso3 : "SHN",numberCode : "654",phoneCode : "290"},
  {_id : "180",shortName : "KN",longName : "Saint Kitts and Nevis",iso3 : "KNA",numberCode : "659",phoneCode : "1869"},
  {_id : "181",shortName : "LC",longName : "Saint Lucia",iso3 : "LCA",numberCode : "662",phoneCode : "1758"},
  {_id : "182",shortName : "PM",longName : "Saint Pierre and Miquelon",iso3 : "SPM",numberCode : "666",phoneCode : "508"},
  {_id : "183",shortName : "VC",longName : "Saint Vincent and the Grenadines",iso3 : "VCT",numberCode : "670",phoneCode : "1784"},
  {_id : "184",shortName : "WS",longName : "Samoa",iso3 : "WSM",numberCode : "882",phoneCode : "684"},
  {_id : "185",shortName : "SM",longName : "San Marino",iso3 : "SMR",numberCode : "674",phoneCode : "378"},
  {_id : "186",shortName : "ST",longName : "Sao Tome and Principe",iso3 : "STP",numberCode : "678",phoneCode : "239"},
  {_id : "187",shortName : "SA",longName : "Saudi Arabia",iso3 : "SAU",numberCode : "682",phoneCode : "966"},
  {_id : "188",shortName : "SN",longName : "Senegal",iso3 : "SEN",numberCode : "686",phoneCode : "221"},
  {_id : "189",shortName : "RS",longName : "Serbia and Montenegro",iso3 : "",numberCode : "",phoneCode : "381"},
  {_id : "190",shortName : "SC",longName : "Seychelles",iso3 : "SYC",numberCode : "690",phoneCode : "248"},
  {_id : "191",shortName : "SL",longName : "Sierra Leone",iso3 : "SLE",numberCode : "694",phoneCode : "232"},
  {_id : "192",shortName : "SG",longName : "Singapore",iso3 : "SGP",numberCode : "702",phoneCode : "65"},
  {_id : "193",shortName : "SK",longName : "Slovakia",iso3 : "SVK",numberCode : "703",phoneCode : "421"},
  {_id : "194",shortName : "SI",longName : "Slovenia",iso3 : "SVN",numberCode : "705",phoneCode : "386"},
  {_id : "195",shortName : "SB",longName : "Solomon Islands",iso3 : "SLB",numberCode : "90",phoneCode : "677"},
  {_id : "196",shortName : "SO",longName : "Somalia",iso3 : "SOM",numberCode : "706",phoneCode : "252"},
  {_id : "197",shortName : "ZA",longName : "South Africa",iso3 : "ZAF",numberCode : "710",phoneCode : "27"},
  {_id : "198",shortName : "GS",longName : "South Georgia and the South Sandwich Islands",iso3 : "",numberCode : "",phoneCode : "0"},
  {_id : "199",shortName : "ES",longName : "Spain",iso3 : "ESP",numberCode : "724",phoneCode : "34"},
  {_id : "200",shortName : "LK",longName : "Sri Lanka",iso3 : "LKA",numberCode : "144",phoneCode : "94"},
  {_id : "201",shortName : "SD",longName : "Sudan",iso3 : "SDN",numberCode : "736",phoneCode : "249"},
  {_id : "202",shortName : "SS",longName : "South Sudan",iso3 : "SSD",numberCode : "728",phoneCode : "211"},
  {_id : "203",shortName : "SR",longName : "Suriname",iso3 : "SUR",numberCode : "740",phoneCode : "597"},
  {_id : "204",shortName : "SJ",longName : "Svalbard and Jan Mayen",iso3 : "SJM",numberCode : "744",phoneCode : "47"},
  {_id : "205",shortName : "SZ",longName : "Swaziland",iso3 : "SWZ",numberCode : "748",phoneCode : "268"},
  {_id : "206",shortName : "SE",longName : "Sweden",iso3 : "SWE",numberCode : "752",phoneCode : "46"},
  {_id : "207",shortName : "CH",longName : "Switzerland",iso3 : "CHE",numberCode : "756",phoneCode : "41"},
  {_id : "208",shortName : "SY",longName : "Syrian Arab Republic",iso3 : "SYR",numberCode : "760",phoneCode : "963"},
  {_id : "209",shortName : "TW",longName : "Taiwan, Province of China",iso3 : "TWN",numberCode : "158",phoneCode : "886"},
  {_id : "210",shortName : "TJ",longName : "Tajikistan",iso3 : "TJK",numberCode : "762",phoneCode : "992"},
  {_id : "211",shortName : "TZ",longName : "Tanzania, United Republic of",iso3 : "TZA",numberCode : "834",phoneCode : "255"},
  {_id : "212",shortName : "TH",longName : "Thailand",iso3 : "THA",numberCode : "764",phoneCode : "66"},
  {_id : "213",shortName : "TL",longName : "Timor-Leste",iso3 : "",numberCode : "",phoneCode : "670"},
  {_id : "214",shortName : "TG",longName : "Togo",iso3 : "TGO",numberCode : "768",phoneCode : "228"},
  {_id : "215",shortName : "TK",longName : "Tokelau",iso3 : "TKL",numberCode : "772",phoneCode : "690"},
  {_id : "216",shortName : "TO",longName : "Tonga",iso3 : "TON",numberCode : "776",phoneCode : "676"},
  {_id : "217",shortName : "TT",longName : "Trin_idad and Tobago",iso3 : "TTO",numberCode : "780",phoneCode : "1868"},
  {_id : "218",shortName : "TN",longName : "Tunisia",iso3 : "TUN",numberCode : "788",phoneCode : "216"},
  {_id : "219",shortName : "TR",longName : "Turkey",iso3 : "TUR",numberCode : "792",phoneCode : "90"},
  {_id : "220",shortName : "TM",longName : "Turkmenistan",iso3 : "TKM",numberCode : "795",phoneCode : "7370"},
  {_id : "221",shortName : "TC",longName : "Turks and Caicos Islands",iso3 : "TCA",numberCode : "796",phoneCode : "1649"},
  {_id : "222",shortName : "TV",longName : "Tuvalu",iso3 : "TUV",numberCode : "798",phoneCode : "688"},
  {_id : "223",shortName : "UG",longName : "Uganda",iso3 : "UGA",numberCode : "800",phoneCode : "256"},
  {_id : "224",shortName : "UA",longName : "Ukraine",iso3 : "UKR",numberCode : "804",phoneCode : "380"},
  {_id : "225",shortName : "AE",longName : "United Arab Emirates",iso3 : "ARE",numberCode : "784",phoneCode : "971"},
  {_id : "226",shortName : "GB",longName : "United Kingdom",iso3 : "GBR",numberCode : "826",phoneCode : "44"},
  {_id : "227",shortName : "US",longName : "United States",iso3 : "USA",numberCode : "840",phoneCode : "1"},
  {_id : "228",shortName : "UM",longName : "United States Minor Outlying Islands",iso3 : "",numberCode : "",phoneCode : "1"},
  {_id : "229",shortName : "UY",longName : "Uruguay",iso3 : "URY",numberCode : "858",phoneCode : "598"},
  {_id : "230",shortName : "UZ",longName : "Uzbekistan",iso3 : "UZB",numberCode : "860",phoneCode : "998"},
  {_id : "231",shortName : "VU",longName : "Vanuatu",iso3 : "VUT",numberCode : "548",phoneCode : "678"},
  {_id : "232",shortName : "VE",longName : "Venezuela",iso3 : "VEN",numberCode : "862",phoneCode : "58"},
  {_id : "233",shortName : "VN",longName : "Viet Nam",iso3 : "VNM",numberCode : "704",phoneCode : "84"},
  {_id : "234",shortName : "VG",longName : "Virgin Islands, British",iso3 : "VGB",numberCode : "92",phoneCode : "1284"},
  {_id : "235",shortName : "VI",longName : "Virgin Islands, U.s.",iso3 : "VIR",numberCode : "850",phoneCode : "1340"},
  {_id : "236",shortName : "WF",longName : "Wallis and Futuna",iso3 : "WLF",numberCode : "876",phoneCode : "681"},
  {_id : "237",shortName : "EH",longName : "Western Sahara",iso3 : "ESH",numberCode : "732",phoneCode : "212"},
  {_id : "238",shortName : "YE",longName : "Yemen",iso3 : "YEM",numberCode : "887",phoneCode : "967"},
  {_id : "239",shortName : "ZM",longName : "Zambia",iso3 : "ZMB",numberCode : "894",phoneCode : "260"},
  {_id : "240",shortName : "ZW",longName : "Zimbabwe",iso3 : "ZWE",numberCode : "716",phoneCode : "263"}
];
