
module.exports.timezoneSeed = [
  {_id : "1",name : "(GMT-11:00} International Date Line West",value : "Pacific/Kwajalein"},
  {_id : "2",name : "(GMT-11:00} Midway Island",value : "Pacific/Midway"},
  {_id : "3",name : "(GMT-11:00} Samoa",value : "Pacific/Samoa"},
  {_id : "4",name : "(GMT-10:00} Hawaii",value : "Pacific/Honolulu"},
  {_id : "5",name : "(GMT-10:00} Pacific/Honolulu",value : "Pacific/Honolulu"},
  {_id : "6",name : "(GMT-09:00} Alaska",value : "US/Alaska"},
  {_id : "7",name : "(GMT-08:00} America/Los_Angeles",value : "America/Los_Angeles"},
  {_id : "8",name : "(GMT-08:00} Pacific Time (US &amp; Canada}",value : "America/Los_Angeles"},
  {_id : "9",name : "(GMT-08:00} Tijuana",value : "America/Tijuana"},
  {_id : "10",name : "(GMT-07:00} America/Denver",value : "America/Denver"},
  {_id : "11",name : "(GMT-07:00} America/Phoenix",value : "America/Phoenix"},
  {_id : "12",name : "(GMT-07:00} Arizona",value : "US/Arizona"},
  {_id : "13",name : "(GMT-07:00} Chihuahua",value : "America/Chihuahua"},
  {_id : "14",name : "(GMT-07:00} Mazatlan",value : "America/Mazatlan"},
  {_id : "15",name : "(GMT-07:00} Mountain Time (US &amp; Canada}",value : "US/Mountain"},
  {_id : "16",name : "(GMT-06:00} America/Chicago",value : "America/Chicago"},
  {_id : "17",name : "(GMT-06:00} America/Mexico_City",value : "America/Mexico_City"},
  {_id : "18",name : "(GMT-06:00} Central America",value : "America/Managua"},
  {_id : "19",name : "(GMT-06:00} Central Time (US &amp; Canada}",value : "US/Central"},
  {_id : "20",name : "(GMT-06:00} Guadalajara",value : "America/Mexico_City"},
  {_id : "21",name : "(GMT-06:00} Mexico City",value : "America/Mexico_City"},
  {_id : "22",name : "(GMT-06:00} Monterrey",value : "America/Monterrey"},
  {_id : "23",name : "(GMT-06:00} Saskatchewan",value : "Canada/Saskatchewan"},
  {_id : "24",name : "(GMT-05:00} America/Nassau",value : "America/Nassau"},
  {_id : "25",name : "(GMT-05:00} America/New_York",value : "America/New_York"},
  {_id : "26",name : "(GMT-05:00} America/Port-au-Prince",value : "America/Port-au-Prince"},
  {_id : "27",name : "(GMT-05:00} America/Toronto",value : "America/Toronto"},
  {_id : "28",name : "(GMT-05:00} Bogota",value : "America/Bogota"},
  {_id : "29",name : "(GMT-05:00} Eastern Time (US &amp; Canada}",value : "US/Eastern"},
  {_id : "30",name : "(GMT-05:00} Indiana (East}",value : "US/East-Indiana"},
  {_id : "31",name : "(GMT-05:00} Lima",value : "America/Lima"},
  {_id : "32",name : "(GMT-05:00} Quito",value : "America/Bogota"},
  {_id : "33",name : "(GMT-04:30} Caracas",value : "America/Caracas"},
  {_id : "34",name : "(GMT-04:00} Atlantic Time (Canada}",value : "Canada/Atlantic"},
  {_id : "35",name : "(GMT-04:00} Georgetown",value : "America/Argentina/Buenos_Aires"},
  {_id : "36",name : "(GMT-04:00} La Paz",value : "America/La_Paz"},
  {_id : "37",name : "(GMT-03:30} Newfoundland",value : "Canada/Newfoundland"},
  {_id : "38",name : "(GMT-03:00} America/Argentina/Buenos_Aires",value : "America/Argentina/Buenos_Aires"},
  {_id : "39",name : "(GMT-03:00} America/Cordoba",value : "America/Cordoba"},
  {_id : "40",name : "(GMT-03:00} America/Fortaleza",value : "America/Fortaleza"},
  {_id : "41",name : "(GMT-03:00} America/Montevideo",value : "America/Montevideo"},
  {_id : "42",name : "(GMT-03:00} America/Santiago",value : "America/Santiago"},
  {_id : "43",name : "(GMT-03:00} America/Sao_Paulo",value : "America/Sao_Paulo"},
  {_id : "44",name : "(GMT-03:00} Brasilia",value : "America/Sao_Paulo"},
  {_id : "45",name : "(GMT-03:00} Buenos Aires",value : "America/Argentina/Buenos_Aires"},
  {_id : "46",name : "(GMT-03:00} Greenland",value : "America/Godthab"},
  {_id : "47",name : "(GMT-03:00} Santiago",value : "America/Santiago"},
  {_id : "48",name : "(GMT-02:00} Mid-Atlantic",value : "America/Noronha"},
  {_id : "49",name : "(GMT-01:00} Azores",value : "Atlantic/Azores"},
  {_id : "50",name : "(GMT-01:00} Cape Verde Is.",value : "Atlantic/Cape_Verde"},
  {_id : "51",name : "(GMT+00:00} Africa/Casablanca",value : "Africa/Casablanca"},
  {_id : "52",name : "(GMT+00:00} Atlantic/Canary",value : "Atlantic/Canary"},
  {_id : "53",name : "(GMT+00:00} Atlantic/Reykjavik",value : "Atlantic/Reykjavik"},
  {_id : "54",name : "(GMT+00:00} Casablanca",value : "Africa/Casablanca"},
  {_id : "55",name : "(GMT+00:00} Dublin",value : "Etc/Greenwich"},
  {_id : "56",name : "(GMT+00:00} Edinburgh",value : "Europe/London"},
  {_id : "57",name : "(GMT+00:00} Europe/Dublin",value : "Europe/Dublin"},
  {_id : "58",name : "(GMT+00:00} Europe/Lisbon",value : "Europe/Lisbon"},
  {_id : "59",name : "(GMT+00:00} Europe/London",value : "Europe/London"},
  {_id : "60",name : "(GMT+00:00} Lisbon",value : "Europe/Lisbon"},
  {_id : "61",name : "(GMT+00:00} London",value : "Europe/London"},
  {_id : "62",name : "(GMT+00:00} Monrovia",value : "Africa/Monrovia"},
  {_id : "63",name : "(GMT+00:00} UTC",value : "UTC"},
  {_id : "64",name : "(GMT+01:00} Amsterdam",value : "Europe/Amsterdam"},
  {_id : "65",name : "(GMT+01:00} Belgrade",value : "Europe/Belgrade"},
  {_id : "66",name : "(GMT+01:00} Berlin",value : "Europe/Berlin"},
  {_id : "67",name : "(GMT+01:00} Bern",value : "Europe/Berlin"},
  {_id : "68",name : "(GMT+01:00} Bratislava",value : "Europe/Bratislava"},
  {_id : "69",name : "(GMT+01:00} Brussels",value : "Europe/Brussels"},
  {_id : "70",name : "(GMT+01:00} Budapest",value : "Europe/Budapest"},
  {_id : "71",name : "(GMT+01:00} Copenhagen",value : "Europe/Copenhagen"},
  {_id : "72",name : "(GMT+01:00} Europe/Amsterdam",value : "Europe/Amsterdam"},
  {_id : "73",name : "(GMT+01:00} Europe/Belgrade",value : "Europe/Belgrade"},
  {_id : "74",name : "(GMT+01:00} Europe/Berlin",value : "Europe/Berlin"},
  {_id : "75",name : "(GMT+01:00} Europe/Bratislava",value : "Europe/Bratislava"},
  {_id : "76",name : "(GMT+01:00} Europe/Brussels",value : "Europe/Brussels"},
  {_id : "77",name : "(GMT+01:00} Europe/Budapest",value : "Europe/Budapest"},
  {_id : "78",name : "(GMT+01:00} Europe/Copenhagen",value : "Europe/Copenhagen"},
  {_id : "79",name : "(GMT+01:00} Europe/Ljubljana",value : "Europe/Ljubljana"},
  {_id : "80",name : "(GMT+01:00} Europe/Madrid",value : "Europe/Madrid"},
  {_id : "81",name : "(GMT+01:00} Europe/Monaco",value : "Europe/Monaco"},
  {_id : "82",name : "(GMT+01:00} Europe/Oslo",value : "Europe/Oslo"},
  {_id : "83",name : "(GMT+01:00} Europe/Paris",value : "Europe/Paris"},
  {_id : "84",name : "(GMT+01:00} Europe/Podgorica",value : "Europe/Podgorica"},
  {_id : "85",name : "(GMT+01:00} Europe/Prague",value : "Europe/Prague"},
  {_id : "86",name : "(GMT+01:00} Europe/Rome",value : "Europe/Rome"},
  {_id : "87",name : "(GMT+01:00} Europe/Stockholm",value : "Europe/Stockholm"},
  {_id : "88",name : "(GMT+01:00} Europe/Tirane",value : "Europe/Tirane"},
  {_id : "89",name : "(GMT+01:00} Europe/Vienna",value : "Europe/Vienna"},
  {_id : "90",name : "(GMT+01:00} Europe/Warsaw",value : "Europe/Warsaw"},
  {_id : "91",name : "(GMT+01:00} Europe/Zagreb",value : "Europe/Zagreb"},
  {_id : "92",name : "(GMT+01:00} Europe/Zurich",value : "Europe/Zurich"},
  {_id : "93",name : "(GMT+01:00} Ljubljana",value : "Europe/Ljubljana"},
  {_id : "94",name : "(GMT+01:00} Madrid",value : "Europe/Madrid"},
  {_id : "95",name : "(GMT+01:00} Paris",value : "Europe/Paris"},
  {_id : "96",name : "(GMT+01:00} Prague",value : "Europe/Prague"},
  {_id : "97",name : "(GMT+01:00} Rome",value : "Europe/Rome"},
  {_id : "98",name : "(GMT+01:00} Sarajevo",value : "Europe/Sarajevo"},
  {_id : "99",name : "(GMT+01:00} Skopje",value : "Europe/Skopje"},
  {_id : "100",name : "(GMT+01:00} Stockholm",value : "Europe/Stockholm"},
  {_id : "101",name : "(GMT+01:00} Vienna",value : "Europe/Vienna"},
  {_id : "102",name : "(GMT+01:00} Warsaw",value : "Europe/Warsaw"},
  {_id : "103",name : "(GMT+01:00} West Central Africa",value : "Africa/Lagos"},
  {_id : "104",name : "(GMT+01:00} Zagreb",value : "Europe/Zagreb"},
  {_id : "105",name : "(GMT+02:00} Asia/Beirut",value : "Asia/Beirut"},
  {_id : "106",name : "(GMT+02:00} Asia/Jerusalem",value : "Asia/Jerusalem"},
  {_id : "107",name : "(GMT+02:00} Asia/Nicosia",value : "Asia/Nicosia"},
  {_id : "108",name : "(GMT+02:00} Athens",value : "Europe/Athens"},
  {_id : "109",name : "(GMT+02:00} Bucharest",value : "Europe/Bucharest"},
  {_id : "110",name : "(GMT+02:00} Cairo",value : "Africa/Cairo"},
  {_id : "111",name : "(GMT+02:00} Europe/Athens",value : "Europe/Athens"},
  {_id : "112",name : "(GMT+02:00} Europe/Helsinki",value : "Europe/Helsinki"},
  {_id : "113",name : "(GMT+02:00} Europe/Istanbul",value : "Europe/Istanbul"},
  {_id : "114",name : "(GMT+02:00} Europe/Riga",value : "Europe/Riga"},
  {_id : "115",name : "(GMT+02:00} Europe/Sofia",value : "Europe/Sofia"},
  {_id : "116",name : "(GMT+02:00} Harare",value : "Africa/Harare"},
  {_id : "117",name : "(GMT+02:00} Helsinki",value : "Europe/Helsinki"},
  {_id : "118",name : "(GMT+02:00} Istanbul",value : "Europe/Istanbul"},
  {_id : "119",name : "(GMT+02:00} Jerusalem",value : "Asia/Jerusalem"},
  {_id : "120",name : "(GMT+02:00} Kyiv",value : "Europe/Helsinki"},
  {_id : "121",name : "(GMT+02:00} Pretoria",value : "Africa/Johannesburg"},
  {_id : "122",name : "(GMT+02:00} Riga",value : "Europe/Riga"},
  {_id : "123",name : "(GMT+02:00} Sofia",value : "Europe/Sofia"},
  {_id : "124",name : "(GMT+02:00} Tallinn",value : "Europe/Tallinn"},
  {_id : "125",name : "(GMT+02:00} Vilnius",value : "Europe/Vilnius"},
  {_id : "126",name : "(GMT+03:00} Baghdad",value : "Asia/Baghdad"},
  {_id : "127",name : "(GMT+03:00} Europe/Minsk",value : "Europe/Minsk"},
  {_id : "128",name : "(GMT+03:00} Europe/Moscow",value : "Europe/Moscow"},
  {_id : "129",name : "(GMT+03:00} Kuwait",value : "Asia/Kuwait"},
  {_id : "130",name : "(GMT+03:00} Minsk",value : "Europe/Minsk"},
  {_id : "131",name : "(GMT+03:00} Moscow",value : "Europe/Moscow"},
  {_id : "132",name : "(GMT+03:00} Nairobi",value : "Africa/Nairobi"},
  {_id : "133",name : "(GMT+03:00} Riyadh",value : "Asia/Riyadh"},
  {_id : "134",name : "(GMT+03:00} St. Petersburg",value : "Europe/Moscow"},
  {_id : "135",name : "(GMT+03:00} Volgograd",value : "Europe/Volgograd"},
  {_id : "136",name : "(GMT+03:30} Tehran",value : "Asia/Tehran"},
  {_id : "137",name : "(GMT+04:00} Abu Dhabi",value : "Asia/Muscat"},
  {_id : "138",name : "(GMT+04:00} Asia/Dubai",value : "Asia/Dubai"},
  {_id : "139",name : "(GMT+04:00} Asia/Tbilisi",value : "Asia/Tbilisi"},
  {_id : "140",name : "(GMT+04:00} Baku",value : "Asia/Baku"},
  {_id : "141",name : "(GMT+04:00} Muscat",value : "Asia/Muscat"},
  {_id : "142",name : "(GMT+04:00} Tbilisi",value : "Asia/Tbilisi"},
  {_id : "143",name : "(GMT+04:00} Yerevan",value : "Asia/Yerevan"},
  {_id : "144",name : "(GMT+04:30} Kabul",value : "Asia/Kabul"},
  {_id : "145",name : "(GMT+05:00} Ekaterinburg",value : "Asia/Yekaterinburg"},
  {_id : "146",name : "(GMT+05:00} Indian/Maldives",value : "Indian/Maldives"},
  {_id : "147",name : "(GMT+05:00} Islamabad",value : "Asia/Karachi"},
  {_id : "148",name : "(GMT+05:00} Karachi",value : "Asia/Karachi"},
  {_id : "149",name : "(GMT+05:00} Tashkent",value : "Asia/Tashkent"},
  {_id : "150",name : "(GMT+05:30} Asia/Calcutta",value : "Asia/Calcutta"},
  {_id : "151",name : "(GMT+05:30} Asia/Colombo",value : "Asia/Colombo"},
  {_id : "152",name : "(GMT+05:30} Chennai",value : "Asia/Calcutta"},
  {_id : "153",name : "(GMT+05:30} Kolkata",value : "Asia/Kolkata"},
  {_id : "154",name : "(GMT+05:30} Mumbai",value : "Asia/Calcutta"},
  {_id : "155",name : "(GMT+05:30} New Delhi",value : "Asia/Calcutta"},
  {_id : "156",name : "(GMT+05:30} Sri Jayawardenepura",value : "Asia/Calcutta"},
  {_id : "157",name : "(GMT+05:45} Kathmandu",value : "Asia/Katmandu"},
  {_id : "158",name : "(GMT+06:00} Almaty",value : "Asia/Almaty"},
  {_id : "159",name : "(GMT+06:00} Astana",value : "Asia/Dhaka"},
  {_id : "160",name : "(GMT+06:00} Dhaka",value : "Asia/Dhaka"},
  {_id : "161",name : "(GMT+06:00} Novosibirsk",value : "Asia/Novosibirsk"},
  {_id : "162",name : "(GMT+06:00} Urumqi",value : "Asia/Urumqi"},
  {_id : "163",name : "(GMT+06:30} Rangoon",value : "Asia/Rangoon"},
  {_id : "164",name : "(GMT+07:00} Asia/Bangkok",value : "Asia/Bangkok"},
  {_id : "165",name : "(GMT+07:00} Asia/Jakarta",value : "Asia/Jakarta"},
  {_id : "166",name : "(GMT+07:00} Bangkok",value : "Asia/Bangkok"},
  {_id : "167",name : "(GMT+07:00} Hanoi",value : "Asia/Bangkok"},
  {_id : "168",name : "(GMT+07:00} Jakarta",value : "Asia/Jakarta"},
  {_id : "169",name : "(GMT+07:00} Krasnoyarsk",value : "Asia/Krasnoyarsk"},
  {_id : "170",name : "(GMT+08:00} Asia/Chongqing",value : "Asia/Chongqing"},
  {_id : "171",name : "(GMT+08:00} Asia/Hong_Kong",value : "Asia/Hong_Kong"},
  {_id : "172",name : "(GMT+08:00} Asia/Kuala_Lumpur",value : "Asia/Kuala_Lumpur"},
  {_id : "173",name : "(GMT+08:00} Asia/Macau",value : "Asia/Macau"},
  {_id : "174",name : "(GMT+08:00} Asia/Makassar",value : "Asia/Makassar"},
  {_id : "175",name : "(GMT+08:00} Asia/Shanghai",value : "Asia/Shanghai"},
  {_id : "176",name : "(GMT+08:00} Asia/Taipei",value : "Asia/Taipei"},
  {_id : "177",name : "(GMT+08:00} Beijing",value : "Asia/Hong_Kong"},
  {_id : "178",name : "(GMT+08:00} Chongqing",value : "Asia/Chongqing"},
  {_id : "179",name : "(GMT+08:00} Hong Kong",value : "Asia/Hong_Kong"},
  {_id : "180",name : "(GMT+08:00} Irkutsk",value : "Asia/Irkutsk"},
  {_id : "181",name : "(GMT+08:00} Kuala Lumpur",value : "Asia/Kuala_Lumpur"},
  {_id : "182",name : "(GMT+08:00} Perth",value : "Australia/Perth"},
  {_id : "183",name : "(GMT+08:00} Singapore",value : "Asia/Singapore"},
  {_id : "184",name : "(GMT+08:00} Taipei",value : "Asia/Taipei"},
  {_id : "185",name : "(GMT+08:00} Ulaan Bataar",value : "Asia/Ulan_Bator"},
  {_id : "186",name : "(GMT+09:00} Asia/Seoul",value : "Asia/Seoul"},
  {_id : "187",name : "(GMT+09:00} Asia/Tokyo",value : "Asia/Tokyo"},
  {_id : "188",name : "(GMT+09:00} Osaka",value : "Asia/Tokyo"},
  {_id : "189",name : "(GMT+09:00} Sapporo",value : "Asia/Tokyo"},
  {_id : "190",name : "(GMT+09:00} Seoul",value : "Asia/Seoul"},
  {_id : "191",name : "(GMT+09:00} Tokyo",value : "Asia/Tokyo"},
  {_id : "192",name : "(GMT+09:00} Yakutsk",value : "Asia/Yakutsk"},
  {_id : "193",name : "(GMT+09:30} Adelaide",value : "Australia/Adelaide"},
  {_id : "194",name : "(GMT+09:30} Darwin",value : "Australia/Darwin"},
  {_id : "195",name : "(GMT+10:00} Australia/Brisbane",value : "Australia/Brisbane"},
  {_id : "196",name : "(GMT+10:00} Australia/Hobart",value : "Australia/Hobart"},
  {_id : "197",name : "(GMT+10:00} Australia/Melbourne",value : "Australia/Melbourne"},
  {_id : "198",name : "(GMT+10:00} Australia/Sydney",value : "Australia/Sydney"},
  {_id : "199",name : "(GMT+10:00} Brisbane",value : "Australia/Brisbane"},
  {_id : "200",name : "(GMT+10:00} Canberra",value : "Australia/Canberra"},
  {_id : "201",name : "(GMT+10:00} Guam",value : "Pacific/Guam"},
  {_id : "202",name : "(GMT+10:00} Hobart",value : "Australia/Hobart"},
  {_id : "203",name : "(GMT+10:00} Magadan",value : "Asia/Magadan"},
  {_id : "204",name : "(GMT+10:00} Melbourne",value : "Australia/Melbourne"},
  {_id : "205",name : "(GMT+10:00} Port Moresby",value : "Pacific/Port_Moresby"},
  {_id : "206",name : "(GMT+10:00} Solomon Is.",value : "Asia/Magadan"},
  {_id : "207",name : "(GMT+10:00} Sydney",value : "Australia/Sydney"},
  {_id : "208",name : "(GMT+10:00} Vladivostok",value : "Asia/Vladivostok"},
  {_id : "209",name : "(GMT+11:00} New Caledonia",value : "Asia/Magadan"},
  {_id : "210",name : "(GMT+12:00} Auckland",value : "Pacific/Auckland"},
  {_id : "211",name : "(GMT+12:00} Fiji",value : "Pacific/Fiji"},
  {_id : "212",name : "(GMT+12:00} Kamchatka",value : "Asia/Kamchatka"},
  {_id : "213",name : "(GMT+12:00} Marshall Is.",value : "Pacific/Fiji"},
  {_id : "214",name : "(GMT+12:00} Pacific/Auckland",value : "Pacific/Auckland"},
  {_id : "310",name : "(GMT+12:00} Wellington",value : "Pacific/Auckland"},
  {_id : "216",name : "(GMT+13:00} Nuku&#39;alofa",value : "Pacific/Tongatapu"}
];
